#pragma once

#include <cstdlib>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/wait.h>
#include <dirent.h>
#include <stdexcept>
#include <fstream>
#include <cstdio>
#include <string>
#include <iostream>
#include <istream>
#include <map>
#include <cctype>
#include <algorithm>
#include <unistd.h>
#include <cstring>
#include <sys/time.h>
#include <ctime>
#include <string>
#include <arpa/inet.h>
#include <list>

#include "macros.hpp"
#include "../srcs/utils/utils.hpp"
#include "../srcs/Logger/Logger.hpp"
#include "../srcs/Sockets/webserv-sockets.hpp"
#include "../srcs/Configurations/webserv-configurations.hpp"
#include "../srcs/HTTP/Request.hpp"
#include "../srcs/HTTP/Response.hpp"
#include "../srcs/CGI/CGI.hpp"
#include "../srcs/Servers/Server.hpp"
#include "../srcs/Client/Client.hpp"
#include "../srcs/Servers/HTTPServer.hpp"
#include "../srcs/Servers/WebServer.hpp"
#include "../srcs/Exception/HTTPException.hpp"
